name: pos_pro_tr
description: Türkiye'ye özel POS sistemi.

publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6  # GetX state management
  sqflite: ^2.3.0  # SQLite veritabanı
  path: ^1.8.3  # Dosya yolları için
  intl: ^0.18.1
  fl_chart: ^0.66.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  mobile_scanner: ^5.2.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  crypto: ^3.0.7
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true